openapi: 3.0.2
info:
  title: Risk Data API
  version: 2025.04.d-preview
servers:
  - url: https://{host}/platform/riskdata/v1
    variables:
      host:
        enum:
          - api-euw1.rms.com
          - api-use1.rms.com
        default: api-euw1.rms.com
        description: "Data center that hosts the tenant instance: api-euw1.rms.com or api-use1.rms.com"
security:
  - rms_api_key: []
  - rms_bearer_token: []
x-readme:
  explorer-enabled: false
  samples-languages:
    - json
    - curl
    - python
    - java
    - csharp
    - node
  proxy-enabled: true
  samples-enabled: true
paths:
  /analyses/{analysisId}/output-metrics-info:
    get:
      tags:
        - Analyses
      summary: Get Output Metrics Info
      operationId: getOutputMetricsInfo
      parameters:
        - name: analysisId
          in: path
          description: ID of analysis.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  granularities:
                    type: object
                    properties:
                      lossTables:
                        type: array
                        items:
                          type: object
                          properties:
                            exposureResourceTypeID:
                              type: integer
                            perspectiveCodes:
                              type: array
                              items:
                                type: string
                      stats:
                        type: array
                        items:
                          type: object
                          properties:
                            exposureResourceTypeID:
                              type: integer
                            perspectiveCodes:
                              type: array
                              items:
                                type: string
  
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        logId:
          type: string
  securitySchemes:
    rms_bearer_token:
      type: http
      description: RMS tenant specific bearer token to make authorized requests with temporary life span
      scheme: bearer
      bearerFormat: JWT
    rms_api_key:
      type: apiKey
      name: Authorization
      description: RMS tenant specific api key to make authorized requests
      in: header
